/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#0b1d2b",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#b6c8dc",
        "surface-container-high": "#d7eaff",
        "background": "#f7f9ff",
        "tertiary-fixed-dim": "#98cbff",
        "on-secondary-fixed": "#001d32",
        "tertiary-container": "#004b79",
        "surface-variant": "#cce5ff",
        "primary": "#213342",
        "on-primary": "#ffffff",
        "inverse-surface": "#10334b",
        "surface-dim": "#bedefd",
        "secondary": "#42617d",
        "on-primary-fixed-variant": "#374858",
        "secondary-container": "#bdddff",
        "on-surface-variant": "#43474c",
        "surface": "#f7f9ff",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "inverse-primary": "#b6c8dc",
        "on-secondary-fixed-variant": "#2a4965",
        "surface-container-highest": "#cce5ff",
        "outline": "#74777c",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#e2efff",
        "on-secondary-container": "#43627e",
        "surface-container-low": "#ecf4ff",
        "secondary-fixed": "#cde5ff",
        "tertiary-fixed": "#cfe5ff",
        "on-background": "#001e31",
        "inverse-on-surface": "#e7f2ff",
        "surface-tint": "#4f6071",
        "outline-variant": "#c4c7cc",
        "on-primary-container": "#a6b8cb",
        "primary-fixed": "#d2e4f8",
        "primary-container": "#384959",
        "surface-bright": "#f7f9ff",
        "on-surface": "#001e31",
        "on-tertiary-fixed": "#001d33",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#aacaea",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#86bbf0",
        "tertiary": "#003455",
        "on-tertiary-fixed-variant": "#004a77",
        "navy": "#384959",
        "navy-dark": "#213342",
        "sky-primary": "#2563eb",
        "sky-border": "#88BDF2",
        "sky-light": "#BDDDFC",
        "sky-soft": "#e8f3fe",
        "sky-surface": "#f4f9ff",
        "accent-blue": "#1d4ed8"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.25rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "2rem",
        "gutter-desktop": "1.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-3xl": "4rem",
        "gutter-mobile": "1rem",
        "space-2xs": "0.25rem",
        "margin-mobile": "1rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-2xl": "3rem"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "headline-sm": ["Outfit", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Outfit", "sans-serif"],
        "display-hero": ["Outfit", "sans-serif"],
        "headline-lg-mobile": ["Outfit", "sans-serif"],
        "display-hero-mobile": ["Outfit", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
        "sans": ["Inter", "sans-serif"],
        "headline": ["Outfit", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["16px", { "lineHeight": "24px", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "headline-sm": ["18px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "600" }],
        "body-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.04em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "display-hero": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.03em", "fontWeight": "800" }],
        "headline-lg-mobile": ["26px", { "lineHeight": "34px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "display-hero-mobile": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "headline-md": ["22px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "700" }]
      }
    }
  },
  plugins: [],
}
